    sudo: required

    services:
      - docker

    before_install:
      - docker build -t tsetsongdevops/react-test -f ./client/Dockerfile.dev ./client

    script:
      - docker run -e CI=true tsetsongdevops/react-test npm test

    after_success:
      - docker build -t tsetsongdevops/multi-client ./client
      - docker build -t tsetsongdevops/multi-nginx  ./nginx
      - docker build -t tsetsongdevops/multi-server ./server
      - docker build -t tsetsongdevops/multi-worker ./worker
      # Log in into docker CLI
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
      # push built images and push them into docker hub
      - docker push tsetsongdevops/multi-client
      - docker push tsetsongdevops/multi-nginx
      - docker push tsetsongdevops/multi-server
      - docker push tsetsongdevops/multi-worker

    deploy:
      provider: elasticbeanstalk
      region: 'ap-southeast-1'
      app: 'multi-containers'
      env: 'Multicontainers-env'
      bucket_name: 'elasticbeanstalk-ap-southeast-1-708339594433'
      bucket_path: 'multi-containers'
      on:
        branch: master
      access_key_id: $AWS_ACCESS_KEY
      secret_access_key: $AWS_SECRET_KEY

      