#!/bin/bash
docker system prune -f
docker rmi $(docker image list -a -q)
docker volume prune -f
docker builder prune -f
docker system df

docker-compose -f docker-compose-dev.yml build --no-cache
docker-compose -f docker-compose-dev.yml up